# ==============================================================================
# 🌟 (Global Settings)
# ==============================================================================
globals:
  scale: 16
  lq_patch_size: 24
 
# ==============================================================================
# Global & Trainer Configuration
# ==============================================================================
trainer:
  max_epochs: 300
  accelerator: "gpu"
  devices: [0]               # Use list for specific GPUs, e.g., [0, 1]
  precision: "bf16-mixed"      # FP16 mixed precision for faster training
  log_every_n_steps: 10
  check_val_every_n_epoch: 3
  accumulate_grad_batches: 2


# ==============================================================================
# DataModule Configuration (SRDataModule)
# ==============================================================================
data:
  type: GuidedSRDataModule

  # Path configs (Replace with your actual dataset paths)
  train_lr_dir: "/data/RiceSR2024/RGB-SAR/dataset/train/LR_bicubic"
  train_hr_dir: "/data/RiceSR2024/RGB-SAR/dataset/train/GT"
  train_guide_dir: "/data/RiceSR2024/RGB-SAR/dataset/train/RGB"
  val_lr_dir: "/data/RiceSR2024/RGB-SAR/dataset/val/LR_bicubic"
  val_hr_dir: "/data/RiceSR2024/RGB-SAR/dataset/val/GT"
  val_guide_dir: "/data/RiceSR2024/RGB-SAR/dataset/val/RGB"
  test_lr_dir: "/data/RiceSR2024/RGB-SAR/dataset/test/LR_bicubic"   # Optional
  test_hr_dir: "/data/RiceSR2024/RGB-SAR/dataset/test/GT"    # Optional
  test_guide_dir: "/data/RiceSR2024/RGB-SAR/dataset/test/RGB"
  
  # DataLoader configs
  batch_size: 8
  num_workers: 8
  
  # Image transformation configs
  lq_patch_size: ${globals.lq_patch_size}   # The size to crop from Low-Res image
  scale: ${globals.scale}                   # Upsampling factor. HR patch will be 32 * 4 = 128

  image_range: "-1~1"

# ==============================================================================
# Ema decay
# ==============================================================================
ema_decay: 0.999


# ==============================================================================
# LightningModule Configuration (SRDiffusionModule)
# ==============================================================================
lightning_module:
  target: UGSRLightningModule
  params:
    eval_crop_border: ${globals.scale}        # Same as scale factor to ignore boundaries during evaluation

    optimizer_config:
      lr: 2.0e-4
      weight_decay: 0.0
      betas: [0.9, 0.999]

    # ----------------------------------------------------------------------------
    # Learning Rate Scheduler
    # ----------------------------------------------------------------------------
    lr_scheduler_config:
      type: "MultiStepLR"
      milestones: [100]
      gamma: 0.1

    # ----------------------------------------------------------------------------
    # Network
    # ----------------------------------------------------------------------------
    network_config:
      target: UGSRGenerator
      params:
        scale_factor: ${globals.scale}
        in_channels: 3
        guide_channels: 3


# ==============================================================================
# Image Logger
# ==============================================================================
image_logger:
  log_batch_freq: 1
  max_images: 8
