# ==============================================================================
# 🌟 (Global Settings)
# ==============================================================================
globals:
  scale: 4
  lq_patch_size: 64

# ==============================================================================
# Global & Trainer Configuration
# ==============================================================================
trainer:
  max_epochs: 300
  accelerator: "gpu"
  devices: [0]               # Use list for specific GPUs, e.g., [0, 1]
  precision: "bf16-mixed"      # FP16 mixed precision for faster training
  log_every_n_steps: 10
  check_val_every_n_epoch: 3


# ==============================================================================
# DataModule Configuration (SRDataModule)
# ==============================================================================
data:
  # Path configs (Replace with your actual dataset paths)
  train_img_dir: "/data/RiceSR2024/RGB-SAR/dataset/train/LR_bicubic"
  train_gt_dir: "/data/RiceSR2024/RGB-SAR/dataset/train/GT"
  val_img_dir: "/data/RiceSR2024/RGB-SAR/dataset/val/LR_bicubic"
  val_gt_dir: "/data/RiceSR2024/RGB-SAR/dataset/val/GT"
  test_img_dir: "/data/RiceSR2024/RGB-SAR/dataset/test/LR_bicubic"   # Optional
  test_gt_dir: "/data/RiceSR2024/RGB-SAR/dataset/test/GT"    # Optional
  
  # DataLoader configs
  batch_size: 16
  num_workers: 8
  
  # Image transformation configs
  lq_patch_size: ${globals.lq_patch_size}   # The size to crop from Low-Res image
  scale: ${globals.scale}                   # Upsampling factor. HR patch will be 32 * 4 = 128

  image_range: "-1~1"

# ==============================================================================
# Ema decay
# ==============================================================================
ema_decay: 0.999


# ==============================================================================
# LightningModule Configuration (SRDiffusionModule)
# ==============================================================================
lightning_module:
  target: ResShiftDiffusionModule
  params:
    eval_crop_border: ${globals.scale}        # Same as scale factor to ignore boundaries during evaluation

    optimizer_config:
      lr: 5e-5
      weight_decay: 0.0
      betas: [0.9, 0.999]

    # ----------------------------------------------------------------------------
    # Learning Rate Scheduler
    # ----------------------------------------------------------------------------
    lr_scheduler_config:
      type: "cosin"
      warmup_epoch: 5
      T_max: 295  # 5 epoch warmup
      eta_min: 2e-5
      

    # ----------------------------------------------------------------------------
    # Network
    # ----------------------------------------------------------------------------
    network_config:
      target: UNetModelSwin
      params:
        image_size: ${globals.lq_patch_size}
        in_channels: 3   # 需要改成对应的Latent Space的Dimention
        model_channels: 160
        out_channels: 3  # The same as the in channels
        attention_resolutions: [64,32,16,8] # 全覆盖，需要进行对应的修改
        dropout: 0
        channel_mult: [1, 2, 2, 4]
        num_res_blocks: [2, 2, 2, 2]
        conv_resample: True
        dims: 2
        use_fp16: False
        num_head_channels: 32
        use_scale_shift_norm: True
        resblock_updown: False
        swin_depth: 2
        swin_embed_dim: 192
        window_size: 8
        mlp_ratio: 4
        cond_lq: True
        lq_size: ${globals.lq_patch_size}


    diffusion_config:
      target: create_gaussian_diffusion
      params:
        sf: ${globals.scale} 
        schedule_name: exponential
        schedule_kwargs:
          power: 0.3
        etas_end: 0.99
        steps: 15
        min_noise_level: 0.04
        kappa: 2.0
        weighted_mse: False
        predict_type: xstart
        timestep_respacing: ~
        scale_factor: 1.0
        normalize_input: True
        latent_flag: True

    autoencoder_config:
      target: VQModelResShift
      params:
        embed_dim: 3
        n_embed: 8192
        ddconfig:
          double_z: False
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0

    autoencoder_ckpt_path: logs/VQGAN/X4/version_15/best-epoch=194-val/psnr=27.2524.ckpt

# ==============================================================================
# Image Logger
# ==============================================================================
image_logger:
  log_batch_freq: 1
  max_images: 8
